#!/usr/bin/env bash
# Script to get information about subdomains

get_subdomain_info() {
    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        answer=$(dig "$sub.$domain" +short)
        record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/{getline; print $4}')
        echo "The subdomain $sub is a $record_type record and points to $answer"
    done
}
get_subdomain_info "$1" "$2"